'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Games", [
      {
        title: "Mario Bros.",
        year: 1983,
        platformId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Bros.",
        year: 1985, 
        platformId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Bros. 2",
        year: 1988, 
        platformId: 2, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Bros. 3",
        year: 1990,
        platformId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Bros./Duck Hunt/Track Meet",
        year: 1990,
        platformId: 2, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Dr. Mario",
        year: 1990,
        platformId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario is Missing!",
        year: 1993,
        platformId: 2, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario's Time Machine",
        year: 1994, 
        platformId: 3, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario 64",
        year: 1996, 
        platformId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Kart 64",
        year: 1996,
        platformId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      {
        title: "Mario Party", 
        year: 1998,
        platformId: 4, 
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      {
        title: "Mario Party 2", 
        year: 1999,
        platformId: 4, 
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      {
        title: "Mario Party 3", 
        year: 2000, 
        platformId: 4, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Tennis", 
        year: 2000, 
        platformId: 4, 
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      {
        title: "Mario Golf", 
        year: 1999, 
        platformId: 4, 
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      {
        title: "Paper Mario",
        year: 2000,
        platformId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      }, 
      {
        title: "Dr. Mario 64",
        year: 2001,
        platformId: 4, 
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Land",
        year: 1989,
        platformId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Dr. Mario",
        year: 1989,
        platformId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Land 2: 6 Golden Coins",
        year: 1992,
        platformId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario's Picross",
        year: 1995,
        platformId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Wario Land: Super Mario Land 3",
        year: 1993,
        platformId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario & Wario",
        year: 1993,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario's Early Years! Fun with Letters",
        year: 1994,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario's Early Years! Fun with Numbers",
        year: 1994,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario's Early Years! Preschool Fun",
        year: 1994,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Is Missing!",
        year: 1993,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Paint",
        year: 1992,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario's Time Machine",
        year: 1993,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario's Super Picross",
        year: 1993,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario All-Stars",
        year: 1995,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Kart",
        year: 1992,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario RPG: Legend of the Seven Stars",
        year: 1993,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario World",
        year: 1991,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario World 2: Yoshi's Island",
        year: 1995,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Tetris & Dr. Mario",
        year: 1994,
        platformId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Golf",
        year: 1999,
        platformId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Bros. Deluxe",
        year: 1999,
        platformId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Tennis",
        year: 2000,
        platformId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Dr. mario & Puzzle League",
        year: 2005,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario & Luigi: Superstar Saga",
        year: 2002,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Golf: Advance Tour",
        year: 2004,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Kart: Super Circuit",
        year: 2001,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Party Advance",
        year: 2005,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Pinball Land",
        year: 2004,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario Tennis: Power Tour",
        year: 2005,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Mario vs. Donkey Kong",
        year: 2004,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Advance",
        year: 2001,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Advance 2: Super Mario World",
        year: 2001,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Advance 3: Yoshi's Island",
        year: 2002,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Super Mario Advance 4: Super Mario Bros. 3",
        year: 2003,
        platformId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ])
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Games", null, {})
  }
}
